name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - master # 或者 main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'pacountdown-web' # 替换为你的 Cloudflare Pages 项目名称
          directory: './' # 静态文件的根目录
          # Optional: target a specific branch
          # branch: 'production' 